// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/Allen-Digital-OSS/doordarshan-kendra-oss/pkg/app"
	"github.com/Allen-Digital-OSS/doordarshan-kendra-oss/pkg/clients"
	"github.com/Allen-Digital-OSS/doordarshan-kendra-oss/pkg/common"
	"github.com/Allen-Digital-OSS/doordarshan-kendra-oss/pkg/data"
	"github.com/Allen-Digital-OSS/doordarshan-kendra-oss/pkg/handler"
	"github.com/Allen-Digital-OSS/doordarshan-kendra-oss/pkg/server"
	"github.com/Allen-Digital-OSS/doordarshan-kendra-oss/pkg/sfu"
)

// Injectors from wire.go:

// InitializeApp init echo application.
func InitializeApp(appConfig *common.AppConfig, metric *common.Meter, tenantClusterHandlerMap map[string]sfu.IClusterHandler) (*app.Application, error) {
	appMiddleware := server.NewAppMiddleware(appConfig, metric)
	mySQLClient := data.NewMySQLClient(appConfig)
	baseClusterHandler := sfu.NewBaseClusterHandler(mySQLClient)
	signalingPlatformClient := clients.NewSignalingPlatformClient(appConfig)
	logger, err := handler.NewLoggerProvider(appConfig)
	if err != nil {
		return nil, err
	}
	redisClient := data.NewRedisClient(appConfig)
	redisRepository := data.NewRedisRepository(redisClient, appConfig)
	iMeetingV1Handler := handler.NewMeetingV1Handler(tenantClusterHandlerMap, baseClusterHandler, signalingPlatformClient, appConfig, logger, redisRepository)
	serverServer := server.NewServer(appConfig, appMiddleware, iMeetingV1Handler)
	goRoutinePool, err := common.NewGoRoutinePool(appConfig)
	if err != nil {
		return nil, err
	}
	application := app.NewApplication(appConfig, metric, serverServer, goRoutinePool)
	return application, nil
}
